### ISSUE TITLE
Add the possibility of copying and pasting

### ISSUE THREAD

**Issue by YasinC2** [Akascape/Ascify-Art#3]
Hello;
Thanks for your cool app.
Please add the ability to copy and paste in the character entry section.

**Comment by Akascape** [comment]
@YasinC2 Sure, I will add it soon!

**Comment by YasinC2** [comment]
@Akascape 
I just realized that the keyboard shortcuts work for copy and paste, only the mouse doesn't.

**Comment by Akascape** [comment]
@YasinC2 Implemented a new right click menu:
![image](https://github.com/Akascape/Ascify-Art/assets/89206401/919a8cd0-5d88-4a93-983d-3411986e956e)
