### ISSUE TITLE
Export the Actual ASCII Art

### ISSUE THREAD

**Issue by favarete** [Akascape/Ascify-Art#4]
Hey, man. AMAZING tool, I managed to generate exactly the result I wanted. But I need to export the actual characters, not the “filtered-image”. 

There's some hidden way to export the characters? Export as html/css to preserve the colors would be perfect. 

If that's not possible today, do you have any advice about a possible implementation? I can try to work on that in my spare time.

**Comment by Akascape** [comment]
> But I need to export the actual characters, not the “filtered-image”.
There's some hidden way to export the characters? Export as html/css to preserve the colors would be perfect.

@favarete Yeah it is possible to export the characters only. i will try to implement it soon.

**Comment by Akascape** [comment]
@favarete Now you can right click on the ascii image and select "copy ascii text" option to export the characters:

![image](https://github.com/Akascape/Ascify-Art/assets/89206401/09cbbe51-dbbf-4205-934c-2e27accd5b45)
