### ISSUE TITLE
Can't open image sequence

### ISSUE THREAD

**Issue by Abbenay** [Akascape/Ascify-Art#5]
Hello, Many tahnks for your amazing app. I'm trying to convert a whole sequence of images, but I can;t make the feature work.

I am running the app with python on a MacOS Monterery - firstly I found that right clicking the open button didn't do anything, then I discovered that I could get the 'import image sequence' dialog to appear by middle clicking my scroll wheel.

However, when I navigate to the folder of images i want to use it always says "No valid image files present in this folder!" - I have tried jpg and png and various different naming schemes. All the images open just fine individually, but when I try to open a sequence with the same files, this always happens.

Is there a special way I should name them or something else I am not doing correctly?

**Comment by Akascape** [comment]
@Abbenay Ok, I have updated the code, please download the new "Ascift-Art.py" file and test.

**Comment by Abbenay** [comment]
Wow! Thanks so much for getting on it so fast. It works perfectly now. All Good. Thank you so much!
